### ISSUE TITLE
extract_rawChunk bug for plotting raw traces

### ISSUE THREAD

**Issue by diogoflduarte** [m-beau/NeuroPyxels#150]
Hi everyone,

The following error stack issues when plotting raw traces from the example page / readme:
``` python
Traceback (most recent call last):
  File "C:\Miniconda3\envs\neuropyxels\lib\site-packages\IPython\core\interactiveshell.py", line 3552, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-cf7a07345f46>", line 1, in <module>
    runfile('C:/Users/diogo/careylab/code/ddcareylab/ephys/python_scripts/trying_neuropyxels.py', wdir='C:/Users/diogo/careylab/code/ddcareylab/ephys/python_scripts')
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.3.5\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.3.5\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/diogo/careylab/code/ddcareylab/ephys/python_scripts/trying_neuropyxels.py", line 64, in <module>
    med_sub=1, whiten=1, hpfilt=1)
  File "C:\Miniconda3\envs\neuropyxels\lib\site-packages\npyx\plot.py", line 1003, in plot_raw_units
    whiten, med_sub, hpfilt, hpfiltf, nRangeWhiten, nRangeMedSub, ignore_ks_chanfilt)
  File "C:\Miniconda3\envs\neuropyxels\lib\site-packages\npyx\inout.py", line 628, in extract_rawChunk
    fname = get_binary_file_path(meta, filt_key)
  File "C:\Miniconda3\envs\neuropyxels\lib\site-packages\npyx\inout.py", line 485, in get_binary_file_path
    relative_path = meta[filt_key]['binary_relative_path']
KeyError: 'ap'
```

and the culprit seems to be a non-flexible input of `extract_rawChunk` (4th arg)

which was coded like this:
```python
rc = extract_rawChunk(dp, times, channels, 'ap', saveData,
                          whiten, med_sub, hpfilt, hpfiltf, nRangeWhiten, nRangeMedSub, ignore_ks_chanfilt)
```

I changed locally to: 
``` python
rc = extract_rawChunk(dp, times, channels, 'highpass', saveData,
                          whiten, med_sub, hpfilt, hpfiltf, nRangeWhiten, nRangeMedSub, ignore_ks_chanfilt)
```
and the traces plotted after that.
Still, is there a better way of doing this, and could you please add a fix?

Thanks,
Diogo

**Comment by m-beau** [comment]
Hi Diogo! I only saw that now, you're one of the first issue posters here sorry for that - this should now be fixed, you can pull from the master branch!

**Comment by m-beau** [comment]
closing this issue
