### ISSUE TITLE
IndexError in funtion trn_filtered

### ISSUE THREAD

**Issue by FranciscoNaveros** [m-beau/NeuroPyxels#336]
When I execute the command predict_cell_types, I´m having the next error:

Traceback (most recent call last):
  File "C:\Users\Usuario\.conda\envs\phy_dev\lib\site-packages\joblib\externals\loky\process_executor.py", line 428, in _process_worker
    r = call_item()
  File "C:\Users\Usuario\.conda\envs\phy_dev\lib\site-packages\joblib\externals\loky\process_executor.py", line 275, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "C:\Users\Usuario\.conda\envs\phy_dev\lib\site-packages\joblib\_parallel_backends.py", line 620, in __call__
    return self.func(*args, **kwargs)
  File "C:\Users\Usuario\.conda\envs\phy_dev\lib\site-packages\joblib\parallel.py", line 288, in __call__
    return [func(*args, **kwargs)
  File "C:\Users\Usuario\.conda\envs\phy_dev\lib\site-packages\joblib\parallel.py", line 288, in <listcomp>
    return [func(*args, **kwargs)
  File "c:\phyllum\neuropyxels-master\npyx\c4\predict_cell_types.py", line 237, in aux_prepare_dataset
    t, _ = trn_filtered(dp, u, period_m=None, again=True, enforced_rp=-1)
  File "c:\phyllum\neuropyxels-master\npyx\spk_t.py", line 772, in trn_filtered
    good_spikes_m, good_fp_start_end, good_fn_start_end = train_quality(dp, unit, period_m,
  File "c:\phyllum\neuropyxels-master\npyx\spk_t.py", line 566, in train_quality
    unit_amp = load_amplitudes(dp, unit, verbose, 'all', again, enforced_rp)
  File "c:\phyllum\neuropyxels-master\npyx\spk_t.py", line 112, in load_amplitudes
    unit_ids = ids(dp, unit, True, verbose, periods, again, enforced_rp)
  File "c:\phyllum\neuropyxels-master\npyx\spk_t.py", line 92, in ids
    indices = indices[~duplicates_m]
IndexError: boolean index did not match indexed array along dimension 0; dimension is 299 but corresponding boolean dimension is 1117
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Usuario\.conda\envs\phy_dev\Scripts\predict_cell_types-script.py", line 33, in <module>
    sys.exit(load_entry_point('npyx', 'console_scripts', 'predict_cell_types')())
  File "c:\phyllum\neuropyxels-master\npyx\c4\predict_cell_types.py", line 513, in main
    prediction_dataset, good_units = prepare_dataset(args)
  File "c:\phyllum\neuropyxels-master\npyx\c4\predict_cell_types.py", line 316, in prepare_dataset
    prediction_dataset, bad_units = prepare_dataset_from_binary_parallel(
  File "c:\phyllum\neuropyxels-master\npyx\c4\predict_cell_types.py", line 263, in prepare_dataset_from_binary_parallel
    dataset_results = Parallel(n_jobs=num_cores, prefer="processes")(
  File "C:\Users\Usuario\.conda\envs\phy_dev\lib\site-packages\joblib\parallel.py", line 1098, in __call__
    self.retrieve()
  File "C:\Users\Usuario\.conda\envs\phy_dev\lib\site-packages\joblib\parallel.py", line 975, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "C:\Users\Usuario\.conda\envs\phy_dev\lib\site-packages\joblib\_parallel_backends.py", line 567, in wrap_future_result
    return future.result(timeout=timeout)
  File "C:\Users\Usuario\.conda\envs\phy_dev\lib\concurrent\futures\_base.py", line 458, in result
    return self.__get_result()
  File "C:\Users\Usuario\.conda\envs\phy_dev\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
IndexError: boolean index did not match indexed array along dimension 0; dimension is 299 but corresponding boolean dimension is 1117

**Comment by m-beau** [comment]
Hey Francisco,

This should be fixed on the cell_type_classifier branch - let's meet and merge all our fixes on the same branch before testing one last time and closing this issue.

**Comment by m-beau** [comment]
This is fixed indeed! Closing.
