### ISSUE TITLE
Ultra dense NP1110 not supported 

### ISSUE THREAD

**Issue by fpedraja** [m-beau/NeuroPyxels#399]
Hi, we encountered the following error while running Phyllum.

Preprocessing track_01_g7_t0.imec0.ap.bin...
    - filtering in time (between 0 and 300 Hz) forward:True, backward:False.
WARNING probe version 1110.0 not handled - post an issue at [www.github.com/m-beau/NeuroPyxels](http://www.github.com/m-beau/NeuroPyxels) and provide your .ap.meta file.
Traceback (most recent call last):
  File "C:\Users\Xenia Gofman\anaconda3\envs\Phyllum_dev\lib\runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\Xenia Gofman\anaconda3\envs\Phyllum_dev\lib\runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "E:\test\kilosort4\preprocess_binary_file.py", line 10, in <module>
    filtered_fname = preprocess_binary_file(dp, filt_key='ap', median_subtract=False, filter_forward=True, filter_backward=False, order=1, move_orig_data=True)
  File "C:\Users\Xenia Gofman\anaconda3\envs\Phyllum_dev\lib\site-packages\npyx\inout.py", line 961, in preprocess_binary_file
    meta = read_metadata(dp)
  File "C:\Users\Xenia Gofman\anaconda3\envs\Phyllum_dev\lib\site-packages\npyx\inout.py", line 48, in read_metadata
    meta = metadata(dp)
  File "C:\Users\Xenia Gofman\anaconda3\envs\Phyllum_dev\lib\site-packages\npyx\inout.py", line 246, in metadata
    raise ValueError(f"Probe version unhandled - bits_encoding unknown.")
ValueError: Probe version unhandled - bits_encoding unknown.

It seems the issue is related to NPYX. Do you think you could add support for the Ultra Dense NP1110? 
Thank you!!

A folder containing a recording and the ap.meta file is available here: https://drive.google.com/drive/folders/13w2qMuFWdxjMhNe98HI42Ev6-rJjW_jx?usp=sharing

**Comment by m-beau** [comment]
I'll assume that the latest version fixed your problem! Closing issue.
